# Generated by Django 5.2.5 on 2025-09-08 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='tickets', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='catalog.department'),
        ),
    ]
