# Generated by Django 5.2.5 on 2025-09-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_closed_at_alter_ticket_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='departement',
            new_name='department',
        ),
    ]
