services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
  db:
    image: postgres
    env_file: .env
    volumes:
      - postgress_data:/var/lib/postgresql/data
volumes:
  postgress_data: