# Generated by Django 5.2.5 on 2025-09-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='level',
        ),
        migrations.AddField(
            model_name='priority',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
