# Generated by Django 5.2.5 on 2025-09-11 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default=None, max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='invalid_rut', message='El RUT debe estar en formato 12345678-9 o 12345678-K', regex='^[0-9]{7,8}-[0-9Kk]$')], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
