# Generated by Django 5.2.5 on 2025-09-11 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_lastname_alter_customuser_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_rut', message='El RUT debe estar en formato 12345678-9 o 12345678-K', regex='^[0-9]{7,8}-[0-9Kk]$')], verbose_name='RUT'),
        ),
    ]
